import 'package:flutter/material.dart';

enum AppLanguage {
  EN('English', Locale('en')),
  FR('Français', Locale('fr')),
  AR('العربية', Locale('ar'));

  final String displayName;
  final Locale locale;
  
  const AppLanguage(this.displayName, this.locale);
}

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'page1': 'Products',
      'page2': 'Orders',
      'profile': 'Profile',
      'depot_name': 'Depot Name',
      'owner_name': 'Owner Full Name',
      'email': 'Email',
      'phone': 'Phone Number',
      'supply_phone': 'Supply Phone',
      'location': 'Location',
      'product_type': 'Type of Product',
      'language': 'Language',
      'active': 'Active',
      'add_product': 'Add Product',
      'edit_product': 'Edit Product',
      'delete_product': 'Delete Product',
      'delete_product_confirm': 'Are you sure you want to delete this product?',
      'product_name': 'Product Name',
      'price': 'Price',
      'quantity': 'Quantity',
      'description': 'Description',
      'specifications': 'Specifications',
      'add_to_cart': 'Add to Cart',
      'required_field': 'This field is required',
      'invalid_number': 'Please enter a valid number',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'add': 'Add',
      'no_products': 'No products yet',
      'no_matching_products': 'No products match your search',
      'no_orders': 'No orders yet',
      'order': 'Order',
      'date': 'Date',
      'status': 'Status',
      'total': 'Total',
      'items': 'Items',
      'complete': 'Complete',
      'volume': 'Volume',
      'weight': 'Weight',
      'search': 'Search products...',
      'filter_by_type': 'Filter by type',
      'all_types': 'All types',
      'sort_by_name': 'Sort by name',
      'sort_by_price': 'Sort by price',
      'sort_by_quantity': 'Sort by quantity',
      'status_pending': 'Pending',
      'status_completed': 'Completed',
      'status_cancelled': 'Cancelled',
      'type_cold': 'Cold',
      'type_covered': 'Covered',
      'type_fragile': 'Fragile',
      'type_liquid': 'Liquid',
      'type_flamble': 'Flammable',
      'status_awaiting': 'Awaiting',
      'status_rejected': 'Rejected',
      'status_in_way': 'In Transit',
      'status_arrived': 'Arrived',
      'status_accident': 'Accident',
      'welcome_back': 'Welcome Back!',
      'sign_in': 'Sign in to continue',
      'sign_in_button': 'Sign In',
      'email_placeholder': 'Enter your email',
      'phone_placeholder': 'Enter your phone number',
      'password_placeholder': 'Enter your password',
      'password': 'Password',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',
      'yes': 'Yes',
      'no': 'No',
      'place_order': 'Place Order',
      'order_summary': 'Order Summary',
      'select_items_first': 'Please select items first',
      'phone_required': 'Phone number is required',
      'order_placed': 'Order placed successfully',
      'status_awaiting_confirmation': 'Awaiting Confirmation',
      'status_delivering': 'Delivering',
      'status_completed': 'Completed',
      'status_canceled': 'Canceled',
      'start_delivering': 'Start Delivering',
    },
    'fr': {
      'page1': 'Produits',
      'page2': 'Commandes',
      'profile': 'Profil',
      'depot_name': 'Nom du Dépôt',
      'owner_name': 'Nom Complet du Propriétaire',
      'email': 'Email',
      'phone': 'Numéro de Téléphone',
      'supply_phone': 'Téléphone de Livraison',
      'location': 'Emplacement',
      'product_type': 'Type de Produit',
      'language': 'Langue',
      'active': 'Actif',
      'add_product': 'Ajouter un Produit',
      'edit_product': 'Modifier le Produit',
      'delete_product': 'Supprimer le Produit',
      'delete_product_confirm': 'Êtes-vous sûr de vouloir supprimer ce produit ?',
      'product_name': 'Nom du Produit',
      'price': 'Prix',
      'quantity': 'Quantité',
      'description': 'Description',
      'specifications': 'Spécifications',
      'add_to_cart': 'Ajouter au Panier',
      'required_field': 'Ce champ est obligatoire',
      'invalid_number': 'Veuillez entrer un nombre valide',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'add': 'Ajouter',
      'no_products': 'Aucun produit pour le moment',
      'no_matching_products': 'Aucun produit ne correspond à votre recherche',
      'no_orders': 'Aucune commande pour le moment',
      'order': 'Commande',
      'date': 'Date',
      'status': 'Statut',
      'total': 'Total',
      'items': 'Articles',
      'complete': 'Terminer',
      'volume': 'Volume',
      'weight': 'Poids',
      'search': 'Rechercher des produits...',
      'filter_by_type': 'Filtrer par type',
      'all_types': 'Tous les types',
      'sort_by_name': 'Trier par nom',
      'sort_by_price': 'Trier par prix',
      'sort_by_quantity': 'Trier par quantité',
      'status_pending': 'En attente',
      'status_completed': 'Terminé',
      'status_cancelled': 'Annulé',
      'type_cold': 'Froid',
      'type_covered': 'Couvert',
      'type_fragile': 'Fragile',
      'type_liquid': 'Liquide',
      'type_flamble': 'Inflammable',
      'status_awaiting': 'En Attente',
      'status_rejected': 'Rejeté',
      'status_in_way': 'En Transit',
      'status_arrived': 'Arrivé',
      'status_accident': 'Accident',
      'welcome_back': 'Bon Retour!',
      'sign_in': 'Connectez-vous pour continuer',
      'sign_in_button': 'Se Connecter',
      'email_placeholder': 'Entrez votre email',
      'phone_placeholder': 'Entrez votre numéro de téléphone',
      'password_placeholder': 'Entrez votre mot de passe',
      'password': 'Mot de passe',
      'logout': 'Déconnexion',
      'logout_confirm': 'Êtes-vous sûr de vouloir vous déconnecter?',
      'yes': 'Oui',
      'no': 'Non',
      'place_order': 'Passer la Commande',
      'order_summary': 'Résumé de la Commande',
      'select_items_first': 'Veuillez sélectionner des articles',
      'phone_required': 'Le numéro de téléphone est requis',
      'order_placed': 'Commande passée avec succès',
      'status_awaiting_confirmation': 'En Attente de Confirmation',
      'status_delivering': 'En Cours de Livraison',
      'status_completed': 'Terminé',
      'status_canceled': 'Annulé',
      'start_delivering': 'Commencer la Livraison',
    },
    'ar': {
      'page1': 'المنتجات',
      'page2': 'الطلبات',
      'profile': 'الملف الشخصي',
      'depot_name': 'اسم المستودع',
      'owner_name': 'الاسم الكامل للمالك',
      'email': 'البريد الإلكتروني',
      'phone': 'رقم الهاتف',
      'supply_phone': 'هاتف التوريد',
      'location': 'الموقع',
      'product_type': 'نوع المنتج',
      'language': 'اللغة',
      'active': 'نشط',
      'add_product': 'إضافة منتج',
      'edit_product': 'تعديل المنتج',
      'delete_product': 'حذف المنتج',
      'delete_product_confirm': 'هل أنت متأكد من حذف هذا المنتج؟',
      'product_name': 'اسم المنتج',
      'price': 'السعر',
      'quantity': 'الكمية',
      'description': 'الوصف',
      'specifications': 'المواصفات',
      'add_to_cart': 'إضافة إلى السلة',
      'required_field': 'هذا الحقل مطلوب',
      'invalid_number': 'الرجاء إدخال رقم صحيح',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'add': 'إضافة',
      'no_products': 'لا توجد منتجات حتى الآن',
      'no_matching_products': 'لا توجد منتجات تطابق بحثك',
      'no_orders': 'لا توجد طلبات حتى الآن',
      'order': 'طلب',
      'date': 'التاريخ',
      'status': 'الحالة',
      'total': 'المجموع',
      'items': 'العناصر',
      'complete': 'إكمال',
      'volume': 'الحجم',
      'weight': 'الوزن',
      'search': 'البحث عن المنتجات...',
      'filter_by_type': 'تصفية حسب النوع',
      'all_types': 'جميع الأنواع',
      'sort_by_name': 'ترتيب حسب الاسم',
      'sort_by_price': 'ترتيب حسب السعر',
      'sort_by_quantity': 'ترتيب حسب الكمية',
      'status_pending': 'قيد الانتظار',
      'status_completed': 'مكتمل',
      'status_cancelled': 'ملغي',
      'type_cold': 'بارد',
      'type_covered': 'مغطى',
      'type_fragile': 'قابل للكسر',
      'type_liquid': 'سائل',
      'type_flamble': 'قابل للاشتعال',
      'status_awaiting': 'قيد الانتظار',
      'status_rejected': 'مرفوض',
      'status_in_way': 'في الطريق',
      'status_arrived': 'وصل',
      'status_accident': 'حادث',
      'welcome_back': 'مرحباً بعودتك!',
      'sign_in': 'سجل الدخول للمتابعة',
      'sign_in_button': 'تسجيل الدخول',
      'email_placeholder': 'أدخل بريدك الإلكتروني',
      'phone_placeholder': 'أدخل رقم هاتفك',
      'password_placeholder': 'أدخل كلمة المرور',
      'password': 'كلمة المرور',
      'logout': 'تسجيل الخروج',
      'logout_confirm': 'هل أنت متأكد من تسجيل الخروج؟',
      'yes': 'نعم',
      'no': 'لا',
      'place_order': 'تقديم الطلب',
      'order_summary': 'ملخص الطلب',
      'select_items_first': 'الرجاء تحديد العناصر أولاً',
      'phone_required': 'رقم الهاتف مطلوب',
      'order_placed': 'تم تقديم الطلب بنجاح',
      'status_awaiting_confirmation': 'في انتظار التأكيد',
      'status_delivering': 'جاري التوصيل',
      'status_completed': 'مكتمل',
      'status_canceled': 'ملغي',
      'start_delivering': 'بدء التوصيل',
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'fr', 'ar'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
} 